apiVersion: certmanager.k8s.io/v1alpha2
kind: Certificate
metadata:
  name: k8s-multi-com-tls
spec:
  secretName: k8s-multi-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: ammarqureshi.com
  dnsNames:
    - ammarqureshi.com
    - www.ammarqureshi.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - ammarqureshi.com
          - www.ammarqureshi.com
